### ISSUE TITLE
App Store and iOS 10-11 compatibility?

### ISSUE THREAD

**Issue by dathinaios** [wdkk/iSuperColliderKit#1]
Hello,

Thank you for working on this :)

A couple of questions:

1. Did you have any success with publishing apps to the App Store?
2. Is it compatible with the latest iOS?

**Comment by wdkk** [comment]
Hello, 

I’m a developer of iSCKit.
Thank you for sending mail, and I’m sorry to reply to late.

Answer, 
1)  We don’t release app on App Store using this kit. Please attension lisence GPL v3.
2) I will do to compatible this kit latest iOS as soon as possible. (Now, don’t compatible, sorry)

iPhoneから送信

H29/10/02 7:38、Dionysis Athinaios <notifications@github.com>のメール:
