### ISSUE TITLE
Trying to build: getting C17 register errors in included files

### ISSUE THREAD

**Issue by mron** [wdkk/iSuperColliderKit#3]
I am getting:
`...iSuperColliderKit/external_libraries/boost/boost/math/special_functions/detail/lanczos_sse2.hpp:54:4: ISO C++17 does not allow 'register' storage class specifier`

I saw you corrected this error in the iSuperColliderKit. How do I get updated external libraries?

**Comment by mron** [comment]
I removed the register specifier. It seems OK to do according to this site: [(https://stackoverflow.com/questions/3207018/register-keyword-in-c]

The internet is never wrong...

**Comment by wdkk-kengo** [comment]
Since lanczos_sse2.hpp is not used in the iSuperColliderKit project, it was not modified for C++17 support.

As already indicated by mron, this can be addressed by removing the register modifier.

The best way is to install a new boost C++.
